name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create results directory
        run: mkdir -p results

      - name: Run Trivy in IaC mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          scan-ref: 'terraform/aws'  # You can also set this to your checkout_path if set manually
          hide-progress: true
          format: 'sarif'
          output: 'results/trivy-results.sarif'  # relative to workspace

      - name: Upload Trivy SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'results/trivy-results.sarif'
          wait-for-processing: true
      - name: Upload SARIF as an artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: sarif-debug
          path: results/trivy-results.sarif
          

